# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcloud-switch" do
  name "gcloud-switch"
  desc "kubectx for gcloud configurations"
  homepage "https://github.com/kostyay/gcloud-switch"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcloud-switch"

  on_macos do
    on_intel do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gcloud-switch_#{version}_darwin_amd64.tar.gz"
      sha256 "b8efa43436b181e9c79d082540c5c0dea037e4d4250d329cf6173266640e439c"
    end
    on_arm do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gcloud-switch_#{version}_darwin_arm64.tar.gz"
      sha256 "e7478cdfee330b4f7b87ff5263db39ce61d3a5dbe8e630db2bc66e450ed9c42c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gcloud-switch_#{version}_linux_amd64.tar.gz"
      sha256 "57415b805019396a3b86acdc1181a0b7881e4fc21189a717ef875c38a57ff070"
    end
    on_arm do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gcloud-switch_#{version}_linux_arm64.tar.gz"
      sha256 "450519bfbed501cb29e143513c6b2a28bc2b81125ee90494ad2ed5b2c5b40de0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gctx"]
    end
  end

  # No zap stanza required
end
