# This file was generated by GoReleaser. DO NOT EDIT.
cask "gctx" do
  name "gctx"
  desc "kubectx for gcloud configurations"
  homepage "https://github.com/kostyay/gcloud-switch"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gctx"

  on_macos do
    on_intel do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gctx_#{version}_darwin_amd64.tar.gz"
      sha256 "faeb922b295fab0ad28fa8be7633b16d99e5aff955c3a4795754d0de74df96b4"
    end
    on_arm do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gctx_#{version}_darwin_arm64.tar.gz"
      sha256 "a7c3ff5be7d97d7dbd7ee3869db390faa5b20e1766c6743c86ab61bbdf6f12c0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gctx_#{version}_linux_amd64.tar.gz"
      sha256 "2f3b75ee6e33bbe09790e9c573df4692a62ac54c6fa9b9f525290dd185c38eeb"
    end
    on_arm do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gctx_#{version}_linux_arm64.tar.gz"
      sha256 "157b5686c156403c70ee6692ccabac23be2e4a46c2bfedb6ac95cf62c2e5eace"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gctx"]
    end
  end

  # No zap stanza required
end
