# This file was generated by GoReleaser. DO NOT EDIT.
cask "gctx" do
  name "gctx"
  desc "kubectx for gcloud configurations"
  homepage "https://github.com/kostyay/gcloud-switch"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gctx"

  on_macos do
    on_intel do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gctx_#{version}_darwin_amd64.tar.gz"
      sha256 "15c8e10ef45bc6ae55630d424c5d912025bad587ba87c329e09bdbe018e86b14"
    end
    on_arm do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gctx_#{version}_darwin_arm64.tar.gz"
      sha256 "18743802d8ac087d58042ece597d56ca3ab45a31231aced3ee728170ce576e5e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gctx_#{version}_linux_amd64.tar.gz"
      sha256 "768c508a5f0e9ee2a0ee142ac5e48f5a0dd78b407d97f02e17426e386345533b"
    end
    on_arm do
      url "https://github.com/kostyay/gcloud-switch/releases/download/v#{version}/gctx_#{version}_linux_arm64.tar.gz"
      sha256 "cd2f15b8bdfa34c7e331a409254aaf38f1a0ea93a9b3945cc26a9c56627b2b43"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gctx"]
    end
  end

  # No zap stanza required
end
