# This file was generated by GoReleaser. DO NOT EDIT.
cask "httpmon" do
  name "httpmon"
  desc "Terminal-native HTTP/HTTPS debugging proxy"
  homepage "https://httpmon.dev"
  version "0.1.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "httpmon"

  on_macos do
    on_intel do
      url "https://github.com/kostyay/httpmon/releases/download/v#{version}/httpmon_#{version}_darwin_amd64.tar.gz"
      sha256 "7fba66f662ccb88fe06cec68a29fda1960584b0a2c3da7990d2fcc41d71dd046"
    end
    on_arm do
      url "https://github.com/kostyay/httpmon/releases/download/v#{version}/httpmon_#{version}_darwin_arm64.tar.gz"
      sha256 "0fbf7e0111ee91add198a317cd37ae3024ec07aa92ba2aa6da8f24b00bd24346"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kostyay/httpmon/releases/download/v#{version}/httpmon_#{version}_linux_amd64.tar.gz"
      sha256 "5ae57fd1899881cd8064fecf2d19d346808189ddfd759d69efb56c3c0192b090"
    end
    on_arm do
      url "https://github.com/kostyay/httpmon/releases/download/v#{version}/httpmon_#{version}_linux_arm64.tar.gz"
      sha256 "3ad1212b2c8613281c17735db74dcd00528df3d9447da2f1d132424fdb0dec71"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/httpmon"]
    end
  end

  # No zap stanza required
end
