# This file was generated by GoReleaser. DO NOT EDIT.
cask "httpmon" do
  name "httpmon"
  desc "Terminal-native HTTP/HTTPS debugging proxy"
  homepage "https://httpmon.dev"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "httpmon"

  on_macos do
    on_intel do
      url "https://github.com/kostyay/httpmon/releases/download/v#{version}/httpmon_#{version}_darwin_amd64.tar.gz"
      sha256 "a334f831b25814811a288fafd1b1d3fcaf9a6e196ce45a6796bfa1b7ba6886c2"
    end
    on_arm do
      url "https://github.com/kostyay/httpmon/releases/download/v#{version}/httpmon_#{version}_darwin_arm64.tar.gz"
      sha256 "c1a2e2692e09ce30c6b66a4b3112ec250280663ba50c787433833fe9627c10e3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kostyay/httpmon/releases/download/v#{version}/httpmon_#{version}_linux_amd64.tar.gz"
      sha256 "142736be37125212e47d577fbfa5acf1addd839be7025c4a296369de26bd2073"
    end
    on_arm do
      url "https://github.com/kostyay/httpmon/releases/download/v#{version}/httpmon_#{version}_linux_arm64.tar.gz"
      sha256 "e7298ba0e64d01e0018d001533d7a416554325135443ee122786c87eb1020458"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/httpmon"]
    end
  end

  # No zap stanza required
end
